#173419083 Fix error on failure to redirect to Dashboard after user login
STACK-UP-3/warriors-frontend pull request #13
Opened 2020-06-19 14:47 UTC by fordarnold

#### What does this PR do?
This PR fixes an issue with User Authentication, the app does not redirect to Dashboard on successful login. 

#### Description of Task to be completed?
- Debug the token checker logic.

#### How should this be manually tested?
> First, you must already have a User account.

- Visit the Login page.
- Enter email and password, then click Sign In.
- You should be redirected to the Dashboard page.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[173419083](https://www.pivotaltracker.com/story/show/173419083)

#### Screenshots
N/A

2020-06-19 14:53 UTC, irfiacre approved these changes

2020-06-19 14:57 UTC, bdushimi approved these changes

2020-06-19 14:58 UTC, bdushimi requested changes
The test coverage has dropped!

2020-06-19 15:08 UTC, fordarnold commented
> The test coverage has dropped!

@bdushimi let's see how to fix that with the team.

2020-06-19 18:56 UTC, fordarnold commented
> The test coverage has dropped!

@bdushimi It's been fixed.

2020-06-21 18:21 UTC, bdushimi approved these changes

2020-06-21 18:21 UTC, merged