171784032 Signup to Barefoot Nomad UI
STACK-UP-3/warriors-frontend pull request #4
Opened 2020-05-20 00:35 UTC by Francois-MUGOROZI

### What the PR does?
User get registration form to signup 
### Description of tasks to be completed
 - add signup form
 - connect with API service to signup new user
### How this should be tested manually?
having node/npm, clone the repo branch, cd into and run "npm install".
Then run "start:dev", the browser will open and navigate to signup

### Relevent Pivotal tracker story
[171784032](https://www.pivotaltracker.com/n/projects/2438874/stories/171784032)

### Screenshoots
**Desktop**
![Capture2](https://user-images.githubusercontent.com/53614123/82391717-77d5fc00-99ee-11ea-89f1-96301c9a7b40.JPG)

**Mobile**
![Capture](https://user-images.githubusercontent.com/53614123/82391730-82909100-99ee-11ea-8867-b3ea84983fc9.JPG)

2020-05-22 15:21 UTC, benshidanny11 requested changes

2020-05-22 15:21 UTC, benshidanny11 commented on src/actions/signupAction.js
> +    const res = await axios.post(`http://localhost:5000/api/v1/users/signup`, {
Great job so far, but however I think you should try to use Heroku URL instead of the Local one.

2020-05-26 17:05 UTC, bdushimi requested changes
1. Once a user visits the signup page, there's no need of keeping/including the signup button on the signup page. I suggest you remove the signup button
2. There's a typo right here `By signimg up`. Kindly fix that.
3. I would be better to have the title above the signup page, taking the remaining width. Instead of it being like this :
`Signup To
  Barefoot Nomad`
Make it look like this Signup To Barefoot Nomad
4. When a user submits the data, can you inactivate the form while waiting for the API response?
5. If an API request fails, the form/page does not show any type of error message of what happened/went wrong. (Note that the error message should be user friendly).
6.Kindly ensure that form validations are handled correctly (incorrect emails, not matching passwords)
7. Regarding the tests, some lines in the signup component are not covered because you did not initialize the state so that all properties have defined values.
8. 

Good job on responsiveness and overall implementation.

2020-05-26 17:05 UTC, bdushimi commented on src/components/auth/Signup.js
> +      signupData.confirmpassword = undefined;
@Francois-MUGOROZI any reason why you're making this property `confirmpassword` undefined?

2020-05-26 17:05 UTC, bdushimi commented on src/constants/urls.js
> +  API_BASE_URL: 'http://localhost:5000/api/v1',
@Francois-MUGOROZI shouldn't this point to heroku backend APIs?

2020-05-26 17:05 UTC, bdushimi commented on src/tests/redux/actions/signup.test.js
> +    const expectedActions = [{ type: SIGNUP_STARTED }];
@Francois-MUGOROZI The signup function/thunk fires about more that one action, you have also to assertain signupSucceded and signupFailed actions too as a result, all lines shall be covered.

2020-05-27 18:32 UTC, irfiacre requested changes
Good job @Francois-MUGOROZI this is good.
But from what I have seen in your implementation of the signup UI there are some things that do not resemble the initial design:
![image](https://user-images.githubusercontent.com/52471122/83058298-747aea00-a058-11ea-8a17-d2b518895ff3.png)

From your UI:

![image](https://user-images.githubusercontent.com/52471122/83058256-61681a00-a058-11ea-9a9b-e38ed6df68eb.png)
+(inputs)
Why?

2020-05-27 18:32 UTC, irfiacre commented on src/assets/styles/auth/common.scss
> +.auth-btn {
I think it would better to separate the `styles`  and the `assets`.

2020-05-27 18:32 UTC, irfiacre commented on src/index.js
> +reactDOM.render(<App/>, window.document.getElementById('root'));
Why did you change this?

2020-05-27 19:45 UTC, Francois-MUGOROZI commented on src/index.js
> +reactDOM.render(<App/>, window.document.getElementById('root'));
In my end it was not working that way

2020-05-29 09:32 UTC, bdushimi commented
@Francois-MUGOROZI Kindly reduce the height of both the picture & footer in order to avoid scrolling on the signup page. No need to scroll on the signup page.

2020-05-29 09:49 UTC, bdushimi commented
@Francois-MUGOROZI The input text errors should appear once a user has finished typing in there and the input text is not onfocus.

2020-05-29 09:53 UTC, bdushimi commented
@Francois-MUGOROZI Regarding password & confirm password input texts, let them have different validations, also change this error message 'Password confirm must match password', it's kind confusing, I suggest you go with "Passwords must match".

2020-05-29 09:53 UTC, bdushimi commented
@Francois-MUGOROZI I think it would look better if you reduce the width of the button "Create Free Account"

2020-05-29 10:00 UTC, bdushimi commented
![Screen Shot 2020-05-29 at 11 54 37](https://user-images.githubusercontent.com/35345818/83247075-5241b300-a1a3-11ea-92a8-a2591add9460.png)

There's a CORS error, I am getting.

2020-05-29 10:01 UTC, bdushimi commented
@Francois-MUGOROZI let this title "Signup To Barefoot Nomad" be centered as well.

2020-06-05 07:26 UTC, irfiacre approved these changes

2020-06-05 07:30 UTC, irfiacre commented on src/services/example.service.js
> +// carryout the first action
May be you could delete this file

2020-06-05 07:31 UTC, irfiacre approved these changes

2020-06-08 06:15 UTC, bdushimi approved these changes

2020-06-08 06:15 UTC, merged